export const SIGNGU = [
  { name: '춘천시', DongSignguCd: '110' },
  { name: '원주시', DongSignguCd: '130' },
  { name: '강릉시', DongSignguCd: '150' },
  { name: '동해시', DongSignguCd: '170' },
  { name: '태백시', DongSignguCd: '190' },
  { name: '속초시', DongSignguCd: '210' },
  { name: '삼척시', DongSignguCd: '230' },
  { name: '홍천군', DongSignguCd: '720' },
  { name: '횡성군', DongSignguCd: '730' },
  { name: '영월군', DongSignguCd: '750' },
  { name: '평창군', DongSignguCd: '760' },
  { name: '정선군', DongSignguCd: '770' },
  { name: '철원군', DongSignguCd: '780' },
  { name: '화천군', DongSignguCd: '790' },
  { name: '양구군', DongSignguCd: '800' },
  { name: '인제군', DongSignguCd: '810' },
  { name: '고성군', DongSignguCd: '820' },
  { name: '양양군', DongSignguCd: '830' },
] as const;
